// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/colorways/Coastal.tsx": () => import("../components/mockups/colorways/Coastal.tsx"),
  "./components/mockups/colorways/Current.tsx": () => import("../components/mockups/colorways/Current.tsx"),
  "./components/mockups/colorways/HarvestTable.tsx": () => import("../components/mockups/colorways/HarvestTable.tsx")
};
